# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5288e6a78b9e0a1897545234e9465f6783e7733e73644ce9143dedb9099bc9668654f9e85bf69859e8f43cab732d9b662c2d07a2eb1a7c8176a567129156c576

test:
  secret_key_base: 7c6803518dc19abaf032d0223cd0c28074ef2d4fb469e361dad01efcb6b0043f93becb3837c3810f0fb5b75dfcd4fab9f33dd5e2a0e24c26a9b03ba9a75f25c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
